# Generated by Django 4.2.6 on 2023-10-18 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_at_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 6, 42, 40, 172232, tzinfo=datetime.timezone.utc)),
        ),
    ]
