# Generated by Django 4.2.6 on 2023-10-19 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 19, 6, 6, 36, 959798, tzinfo=datetime.timezone.utc))),
                ('completed_at', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CO', 'Completed'), ('PE', 'Pending'), ('DR', 'Dropped')], default='PE', max_length=2)),
                ('tags', models.ManyToManyField(to='tasks.tag')),
            ],
        ),
    ]
