# Generated by Django 4.2.6 on 2023-10-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('CO', 'completed'), ('PE', 'Pending'), ('DR', 'Dropped')], default='PE', max_length=2)),
                ('tags', models.ManyToManyField(to='tasks.tag')),
            ],
        ),
    ]
